<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "api" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'The subscribers list does not exist.' => 'Список подписчиков не существует.',
  'The subscribers list does not have any custom field defined.' => 'Список подписчиков не имеет определенного настраиваемого поля.',
  'The campaign does not exist.' => 'Кампании не существует.',
  'Only POST requests allowed for this endpoint.' => 'Для этой конечной точки разрешены только POST-запросы.',
  'You have reached the maximum number of allowed campaigns.' => 'Вы достигли максимального количества разрешенных кампаний.',
  'Please provide a list for this campaign.' => 'Предоставьте список подписчиков для этой кампании.',
  'Provided list does not exist.' => 'Предоставленный список не существует.',
  'Provided list segment does not exist.' => 'Предоставленный сегмент списка не существует.',
  'Provided template does not exist.' => 'Предоставленный шаблон не существует.',
  'It does not seem that you have selected an archive.' => 'Кажется, вы не выбрали архив.',
  'Your archive does not seem to be a valid zip file.' => 'Ваш архив не является действительным zip-файлом.',
  'Cannot write archive in the temporary location.' => 'Невозможно создать архив во временном месте.',
  'Please provide a template for your campaign.' => 'Укажите шаблон своей кампании.',
  'Only PUT requests allowed for this endpoint.' => 'Для этой конечной точки разрешены только PUT-запросы.',
  'Unable to copy the campaign.' => 'Не удалось скопировать кампанию.',
  'The campaign does not allow marking it as sent!' => 'Кампания не позволяет маркировать ее как отправленную!',
  'Only DELETE requests allowed for this endpoint.' => 'Для этой конечной точки разрешены только DELETE-запросы.',
  'This campaign cannot be removed now.' => 'Теперь эту кампанию нельзя удалить.',
  'Customer creation is disabled.' => 'Создание клиента отключено.',
  'Unable to find the specified country, please double check the spelling!' => 'Невозможно найти указанную страну, пожалуйста, дважды проверьте правописание!',
  'Unable to find the specified zone, please double check the spelling!' => 'Невозможно найти указанную зону, пожалуйста, дважды проверьте правописание!',
  'The template does not exist.' => 'Шаблон не существует.',
  'The list does not exist.' => 'Список не существует.',
  'You have reached the maximum number of allowed lists.' => 'Вы достигли максимального количества разрешенных списков.',
  'Unable to copy the list.' => 'Не удалось скопировать список.',
  'The email does not exist.' => 'Адрес электронной почты не существует.',
  'The subscriber does not exist.' => 'Подписчика не существует.',
  'The url hash does not exist.' => 'The url hash does not exist.',
  'The subscriber does not exist in this list.' => 'The subscriber does not exist in this list.',
  'Please provide the subscriber email address.' => 'Please provide the subscriber email address.',
  'Please provide a valid email address.' => 'Please provide a valid email address.',
  'The subscriber already exists in this list.' => 'The subscriber already exists in this list.',
  'This email address is blacklisted.' => 'This email address is blacklisted.',
  'The field {field} is required by the list but it has not been provided!' => 'The field {field} is required by the list but it has not been provided!',
  'The field {field} contains multiple values, which is not supported right now!' => 'The field {field} contains multiple values, which is not supported right now!',
  'Unable to save the subscriber!' => 'Unable to save the subscriber!',
  'Another subscriber with this email address already exists in this list.' => 'Another subscriber with this email address already exists in this list.',
  'Your IP address is not allowed to access this server.' => 'Your IP address is not allowed to access this server.',
  'Invalid API request params. Please refer to the documentation.' => 'Invalid API request params. Please refer to the documentation.',
  'Service Unavailable.' => 'Service Unavailable.',
);
